### ISSUE TITLE
Not able to replicate Basic Stock-List demo in py-lightstreamer

### ISSUE THREAD

**Issue by JonathanHolvey** [dw/py-lightstreamer#3]
I've tried out the Lightstreamer python demo script, but since it only supports paid editions of the Lightstreamer server, I'm having a go with py-lightstreamer instead.

After modifying your barebones example to work with your current script (replacing `client.on_connection_state()` with `client.on_state.listen()` and `table.on_update()` with `table.on_update.listen()`) and substituting the parameters from the [Basic Stock-List demo](https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-python), I end up with this:

	import lightstreamer

	def on_connection_state(state):
	    print 'CONNECTION STATE:', state
	    if state == lightstreamer.STATE_DISCONNECTED:
	        connect()

	def on_update(item_id, row):
	    print 'UPDATE!', row

	def connect():
	    client.create_session(username='', adapter_set='DEMO')
	    table = lightstreamer.Table(client, item_ids='item1|item2', schema='stock_name|last_price',
	    	mode=lightstreamer.MODE_MERGE, data_adapter="MONITOR")
	    table.on_update.listen(on_update)

	client = lightstreamer.LsClient('http://push.lightstreamer.com/')
	client.on_state.listen(on_connection_state)

	connect()
	raw_input('Press CR to exit')
	client.destroy()
	client.join()

However, upon running this in Python 2.7, the connection state endlessly switches between `connecting` and `disconnected`. What am I doing wrong?

I suppose my real question should be: Will py-lightstreamer work with the [Moderato edition](http://www.lightstreamer.com/ls-features) of Lightstreamer, with its very limited selection of client APIs? I'm guessing the answer is probably going to be no.

Cheers,
Jon

**Comment by AlessandroAlinone** [comment]
Jon,
I confirm Lightstreamer Moderato enables the JavaScript clients only. To use any other client technology, including Python, you need Lightstreamer Presto or Vivace. If your current need is for development purpose only, you can safely use the embedded Demo License of Lightstreamer Presto/Vivace, which only limits you to 20 concurrent users. On the other hand, for production needs, a contract is required (you can contact info@lightstreamer.com in this case).

Cheers,
Alessandro

**Comment by JonathanHolvey** [comment]
I thought that was the case. Unfortunately I'm not in control of the server I'm trying to stream from, which provides now playing information for an internet radio station. Thanks for your quick answer.
