### ISSUE TITLE
No handlers could be found for logger "lightstreamer"

### ISSUE THREAD

**Issue by fabifrank** [dw/py-lightstreamer#4]
When trying to create a session, the state will be "disconnected" immediately and after then an error follows: No handlers could be found for logger "lightstreamer"

**Comment by dw** [comment]
Prior to starting the client, run code like the following:

````python
import logging
logging.basicConfig(level=logging.DEBUG)
````

This should allow you to discover the nature of the error.

**Comment by fabifrank** [comment]
Thanks for the quick reply!
`Now` the error is: TypeError: request() got an unexpected keyword argument `'prefetch'`

The traceback:
`  File "/home/debby/Documents/dev/rtfx/source/broker-connection/ig/lightstreamer.py", line 185, in run_and_log
    func(*args, **kwargs)
  File "/home/debby/Documents/dev/rtfx/source/broker-connection/ig/lightstreamer.py", line 554, in _create_session_impl
    req = self._post('create_session.txt', encode_dict(dct))
  File "/home/debby/Documents/dev/rtfx/source/broker-connection/ig/lightstreamer.py", line 409, in _post
    timeout=self._get_request_timeout())
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
`

**Comment by dw** [comment]
Please git pull and try the current HEAD. The requests library renamed and inverted the sense of the prefetch parameter.
